package app.dropper.data

import android.content.ContentResolver
import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import app.dropper.proto.Crypto
import app.dropper.proto.FileNames
import app.dropper.proto.Limits
import app.dropper.security.SecureStore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.filterNotNull
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.withContext
import org.json.JSONArray
import java.io.File
import java.io.IOException

class OutboxException(message: String) : Exception(message)

/**
 * Items waiting to be sent to the PC. Shared content is copied into app-private
 * storage immediately (share-sheet URI grants are temporary), so sending can
 * happen later from the service.
 */
class Outbox(context: Context, private val store: SecureStore, private val history: HistoryRepository) {
    private val dir = File(context.filesDir, "outbox").apply { mkdirs() }
    private val _items = MutableStateFlow(load())
    val items: StateFlow<List<OutboxItem>> = _items.asStateFlow()

    val hasPending: Boolean get() = _items.value.any { it.state == OutboxState.PENDING }

    fun file(id: String) = File(dir, "$id.bin")

    fun find(id: String) = _items.value.firstOrNull { it.id == id }

    suspend fun awaitNextPending(): OutboxItem =
        _items.map { list -> list.firstOrNull { it.state == OutboxState.PENDING } }.filterNotNull().first()

    fun enqueueText(text: String): OutboxItem {
        val bytes = text.toByteArray(Charsets.UTF_8)
        if (bytes.size > Limits.MAX_TEXT) throw OutboxException("Text is larger than 4 MB.")
        val item = OutboxItem(Crypto.newItemId(), ItemKind.TEXT, "", "text/plain", bytes.size.toLong(), text = text)
        add(item)
        return item
    }

    /** Copies a shared content:// URI into the outbox. Call from a background thread. */
    suspend fun importUri(resolver: ContentResolver, uri: Uri, typeHint: String?): OutboxItem = withContext(Dispatchers.IO) {
        var displayName: String? = null
        var declaredSize: Long? = null
        try {
            resolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME, OpenableColumns.SIZE), null, null, null)?.use { c ->
                if (c.moveToFirst()) {
                    if (!c.isNull(0)) displayName = c.getString(0)
                    if (!c.isNull(1)) declaredSize = c.getLong(1)
                }
            }
        } catch (_: Exception) {
            // Some providers don't support OpenableColumns; fall back below.
        }
        val name = FileNames.sanitize(displayName ?: uri.lastPathSegment ?: "file")
        val mime = (try { resolver.getType(uri) } catch (_: Exception) { null })
            ?: typeHint?.takeIf { MIME.matches(it) && !it.contains('*') }
            ?: "application/octet-stream"
        declaredSize?.let {
            if (it > Limits.MAX_FILE) throw OutboxException("$name is larger than 64 GB.")
            if (dir.usableSpace < it + RESERVE) throw OutboxException("Not enough free space on this phone to queue $name.")
        }

        val id = Crypto.newItemId()
        val target = file(id)
        try {
            val input = resolver.openInputStream(uri) ?: throw OutboxException("Couldn't read $name.")
            input.use { inp ->
                target.outputStream().use { out ->
                    val buf = ByteArray(256 * 1024)
                    var total = 0L
                    while (true) {
                        val n = inp.read(buf)
                        if (n < 0) break
                        total += n
                        if (total > Limits.MAX_FILE) throw OutboxException("$name is larger than 64 GB.")
                        out.write(buf, 0, n)
                    }
                }
            }
        } catch (e: OutboxException) {
            target.delete()
            throw e
        } catch (e: SecurityException) {
            target.delete()
            throw OutboxException("Dropper wasn't allowed to read $name.")
        } catch (e: IOException) {
            target.delete()
            throw OutboxException("Couldn't read $name.")
        }
        val item = OutboxItem(id, ItemKind.FILE, name, mime, target.length())
        add(item)
        item
    }

    /** Writes generated bytes as a queued file (debug builds' test hook). */
    suspend fun importGenerated(name: String, size: Long, fill: (ByteArray, Int) -> Unit): OutboxItem = withContext(Dispatchers.IO) {
        val id = Crypto.newItemId()
        val target = file(id)
        target.outputStream().use { out ->
            val buf = ByteArray(256 * 1024)
            var left = size
            while (left > 0) {
                val n = minOf(left, buf.size.toLong()).toInt()
                fill(buf, n)
                out.write(buf, 0, n)
                left -= n
            }
        }
        val item = OutboxItem(id, ItemKind.FILE, FileNames.sanitize(name), "application/octet-stream", size)
        add(item)
        item
    }

    private fun add(item: OutboxItem) {
        _items.update { it + item }
        persist()
        history.add(
            HistoryItem(
                id = item.id,
                direction = Direction.OUT,
                kind = item.kind,
                name = item.name,
                size = item.size,
                mime = item.mime,
                text = item.text,
                status = ItemStatus.QUEUED,
                time = System.currentTimeMillis(),
            ),
        )
    }

    fun markSending(id: String) = history.update(id) { it.copy(status = ItemStatus.SENDING, error = null) }

    fun markDelivered(id: String) {
        removeInternal(id)
        history.update(id) { it.copy(status = ItemStatus.DELIVERED, error = null) }
    }

    /** A transient failure: retried until [MAX_ATTEMPTS], then marked failed (§9). */
    fun markAttemptFailed(id: String, error: String) {
        var failed = false
        _items.update { list ->
            list.map {
                if (it.id != id) it else {
                    val attempts = it.attempts + 1
                    failed = attempts >= MAX_ATTEMPTS
                    it.copy(attempts = attempts, state = if (failed) OutboxState.FAILED else OutboxState.PENDING)
                }
            }
        }
        persist()
        history.update(id) {
            if (failed) it.copy(status = ItemStatus.FAILED, error = error) else it.copy(status = ItemStatus.QUEUED, error = error)
        }
    }

    /** A permanent failure (the PC rejected the item). Kept so the user can retry or remove it. */
    fun markFailed(id: String, error: String) {
        _items.update { list -> list.map { if (it.id == id) it.copy(state = OutboxState.FAILED) else it } }
        persist()
        history.update(id) { it.copy(status = ItemStatus.FAILED, error = error) }
    }

    fun retry(id: String) {
        if (find(id) == null) return
        _items.update { list -> list.map { if (it.id == id) it.copy(state = OutboxState.PENDING, attempts = 0) else it } }
        persist()
        history.update(id) { it.copy(status = ItemStatus.QUEUED, error = null) }
    }

    fun remove(id: String) {
        removeInternal(id)
        history.remove(id)
    }

    fun clearAll() {
        _items.value.forEach { file(it.id).delete() }
        _items.value = emptyList()
        store.delete(FILE)
        dir.listFiles()?.forEach { it.delete() }
    }

    private fun removeInternal(id: String) {
        _items.update { list -> list.filterNot { it.id == id } }
        file(id).delete()
        persist()
    }

    @Synchronized
    private fun persist() {
        val arr = JSONArray()
        _items.value.forEach { arr.put(it.toJson()) }
        try {
            store.write(FILE, arr.toString().toByteArray(Charsets.UTF_8))
        } catch (_: Exception) {
        }
    }

    private fun load(): List<OutboxItem> {
        val raw = store.read(FILE) ?: return emptyList()
        val items = try {
            val arr = JSONArray(String(raw, Charsets.UTF_8))
            (0 until arr.length()).mapNotNull { OutboxItem.fromJson(arr.getJSONObject(it)) }
        } catch (_: Exception) {
            emptyList()
        }
        // Drop file items whose content vanished.
        return items.filter { it.kind == ItemKind.TEXT || file(it.id).isFile }
    }

    companion object {
        const val MAX_ATTEMPTS = 3
        private const val FILE = "outbox.bin"
        private const val RESERVE = 64L * 1024 * 1024
        private val MIME = Regex("^[A-Za-z0-9!#$&^_.+-]{1,64}/[A-Za-z0-9!#$&^_.+*-]{1,128}$")
    }
}
