"""Independent reference implementation of the Dropper v1 key schedule and
packet formats. Generates docs/test-vectors.json, which both the Windows (C#)
and Android (Kotlin) unit tests check against, so the two real implementations
are each verified against a third one rather than against each other.

Run: python tools/gen_test_vectors.py
"""
import base64
import hashlib
import hmac
import json
import pathlib
import struct


def hkdf32(ikm: bytes, info: bytes) -> bytes:
    """HKDF-SHA256 (RFC 5869), salt = 32 zero bytes, L = 32."""
    prk = hmac.new(b"\x00" * 32, ikm, hashlib.sha256).digest()
    return hmac.new(prk, info + b"\x01", hashlib.sha256).digest()


def mac(key: bytes, msg: bytes) -> bytes:
    return hmac.new(key, msg, hashlib.sha256).digest()


def b64u(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()


def sas(sas_key: bytes, pc_fp: bytes, phone_fp: bytes) -> str:
    h = mac(sas_key, pc_fp + phone_fp)
    n = struct.unpack(">I", h[:4])[0] % 1_000_000
    return f"{n:06d}"


def preamble(mode: int, ts_ms: int, nonce: bytes, key: bytes) -> bytes:
    head = b"DRP1" + bytes([mode]) + struct.pack(">Q", ts_ms) + nonce
    return head + mac(key, head)


def disc_request(ts_ms: int, nonce: bytes, disc_key: bytes) -> bytes:
    head = b"DRD1" + struct.pack(">Q", ts_ms) + nonce
    return head + mac(disc_key, head)


def disc_response(ip: str, port: int, nonce: bytes, disc_key: bytes) -> bytes:
    head = b"DRD2" + bytes(int(x) for x in ip.split(".")) + struct.pack(">H", port) + nonce
    return head + mac(disc_key, head)


def frame(ftype: int, body: bytes) -> bytes:
    return struct.pack(">I", 1 + len(body)) + bytes([ftype]) + body


def main() -> None:
    # RFC 5869 test case 3 (zero-length salt/info), first 32 bytes of OKM.
    rfc_ikm = bytes([0x0B] * 22)
    rfc_okm32 = hkdf32(rfc_ikm, b"")
    assert rfc_okm32.hex() == "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d"

    pairing_secret = bytes(range(0x00, 0x20))
    device_secret = bytes(range(0x20, 0x40))
    pc_fp = bytes(range(0xA0, 0xC0))
    phone_fp = bytes(range(0xC0, 0xE0))
    ts_ms = 1_700_000_000_000
    nonce = bytes(range(0x10, 0x20))
    pc_ip = "192.168.2.131"
    port = 47823

    pair_gate_key = hkdf32(pairing_secret, b"dropper/v1/pair-gate")
    pair_proof_key = hkdf32(pairing_secret, b"dropper/v1/pair-proof")
    sas_key = hkdf32(pairing_secret, b"dropper/v1/sas")
    gate_key = hkdf32(device_secret, b"dropper/v1/gate")
    disc_key = hkdf32(device_secret, b"dropper/v1/discovery")
    proof = mac(pair_proof_key, pc_fp + phone_fp)

    hello_json = b'{"v":1,"role":"phone","name":"Test","model":"X","app":"1.0.0"}'

    vectors = {
        "_comment": "Generated by tools/gen_test_vectors.py. All byte strings are lowercase hex unless the key ends in _b64u.",
        "rfc5869_case3": {"ikm": rfc_ikm.hex(), "okm32": rfc_okm32.hex()},
        "inputs": {
            "pairing_secret": pairing_secret.hex(),
            "device_secret": device_secret.hex(),
            "pc_fp": pc_fp.hex(),
            "phone_fp": phone_fp.hex(),
            "ts_ms": ts_ms,
            "nonce": nonce.hex(),
            "pc_ip": pc_ip,
            "port": port,
        },
        "keys": {
            "pair_gate_key": pair_gate_key.hex(),
            "pair_proof_key": pair_proof_key.hex(),
            "sas_key": sas_key.hex(),
            "gate_key": gate_key.hex(),
            "disc_key": disc_key.hex(),
        },
        "pair_proof": proof.hex(),
        "pair_proof_b64u": b64u(proof),
        "sas": sas(sas_key, pc_fp, phone_fp),
        "preamble_session": preamble(0x01, ts_ms, nonce, gate_key).hex(),
        "preamble_pairing": preamble(0x02, ts_ms, nonce, pair_gate_key).hex(),
        "disc_request": disc_request(ts_ms, nonce, disc_key).hex(),
        "disc_response": disc_response(pc_ip, port, nonce, disc_key).hex(),
        "frame_hello": {"type": 1, "body_utf8": hello_json.decode(), "bytes": frame(0x01, hello_json).hex()},
        "frame_ping": frame(0x02, b"").hex(),
        "qr_uri": "dropper://pair?v=1&a=192.168.2.131:47823&k=" + b64u(pc_fp) + "&s=" + b64u(pairing_secret) + "&n=MY-PC",
        "fp_display_pc": " ".join(pc_fp[:16].hex().upper()[i:i + 4] for i in range(0, 32, 4)),
    }

    out = pathlib.Path(__file__).resolve().parent.parent / "docs" / "test-vectors.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(vectors, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(vectors, indent=2))


if __name__ == "__main__":
    main()
